<?php

namespace PlatinumPlace\LaravelDgii\Repositories;

use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Repository for handling the physical storage of XML documents.
 *
 * This class abstracts the interaction with the Laravel filesystem to
 * persist and retrieve tax documents generated by the package.
 */
class StorageRepository
{
    /** @var Filesystem The filesystem disk instance used for persistence. */
    protected Filesystem $storage;

    /**
     * Create a new storage repository instance.
     */
    public function __construct()
    {
        // Initialize the storage disk from configuration
        $this->storage = Storage::disk(config('dgii.storage_disk'));
    }

    /**
     * Save XML content to the configured disk.
     *
     * This method automatically organizes files into a date-based folder
     * structure (Year/Month/Day) and generates unique identifiers.
     *
     * @param  string  $xml  The raw XML content to persist.
     * @param  string|null  $xmlName  Optional suggested base name for the file (defaults to UUID).
     * @return string The relative path where the file was saved.
     */
    public function save(string $xml, ?string $xmlName = null): string
    {
        // Define the folder structure and filename using date and UUIDs
        $xmlPath = sprintf(
            config('dgii.storage_path').'/%s/%s/%s/%s/%s.xml',
            now()->format('Y'),
            now()->format('m'),
            now()->format('d'),
            Str::uuid(),
            $xmlName ?? Str::uuid(),
        );

        // Persist the content to the disk
        $this->storage->put($xmlPath, $xml);

        return $xmlPath;
    }

    /**
     * Retrieve the raw content of a stored file.
     *
     * @param  string  $xmlPath  The relative path of the XML file.
     * @return string The raw XML content retrieved from storage.
     */
    public function get(string $xmlPath): string
    {
        // Fetch the file content from the filesystem
        return $this->storage->get($xmlPath);
    }

    /**
     * Get the absolute server path of a stored file.
     *
     * This is primarily used for attaching files to HTTP requests or
     * for operations that require direct file system access.
     *
     * @param  string  $xmlPath  The relative path of the XML file.
     * @return string The absolute system path.
     */
    public function realPath(string $xmlPath): string
    {
        // Resolve the absolute path through the storage disk
        return $this->storage->path($xmlPath);
    }
}
